name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
          path: "SuikaLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/SuikaLauncher-source SuikaLauncher-${{ env.VERSION }}
          mv SuikaLauncher-macOS-*-Release/SuikaLauncher.zip SuikaLauncher-macOS-${{ env.VERSION }}.zip
          mv SuikaLauncher-macOS-*-Release.dmg/SuikaLauncher.dmg SuikaLauncher-macOS-${{ env.VERSION }}.dmg

          tar --exclude='.git' -czf SuikaLauncher-${{ env.VERSION }}.tar.gz SuikaLauncher-${{ env.VERSION }}

          for d in SuikaLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="SuikaLauncher-Windows-MSVC"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv SuikaLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Suika Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            SuikaLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            SuikaLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            SuikaLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            SuikaLauncher-macOS-${{ env.VERSION }}.zip
            SuikaLauncher-macOS-${{ env.VERSION }}.dmg
            SuikaLauncher-${{ env.VERSION }}.tar.gz
